apiVersion: v1
kind: Service
metadata:
  name: react-serv
  labels:
    app: react-serv
spec:
  selector:
    app: reactt
  ports:
  - port: 3010
    targetPort: 3000
    nodePort: 31515
  type: NodePort
